name: pipreqs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Automatic requirements.txt with Python 3.10

        uses: ekvanox/pipreqs-action@v2.2.1

        with:
          COMMIT_MESSAGE: "docs(requirements.txt): :memo: update requirements file"
