name: pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Setting up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=9.0 --disable=E0611,R1705,C0114 --max-line-length=150 --good-names i,j,f,_,e,r
